# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Counter Node.js CI

on:
  push:
    branches: [ nothing ]
  pull_request:
    branches: [ nothing ]

env:
  node_version: 16.x
  severity_level: 12

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
      - run: yarn

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
      - run: yarn
      - name: Run tests
        run: yarn test --ci --watchAll=false

  integration-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
      - run: yarn
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start

  code-scan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
      - run: yarn
      - name: scan code
        id: run_yarn_audit
        shell: bash
        run: |
          yarn audit --level high || exit_code=$?
          echo "::set-output name=EXIT_CODE::$exit_code"

      - name: Check yarn audit with code ${{ steps.run_yarn_audit.outputs.EXIT_CODE }}
        if: ${{ steps.run_yarn_audit.outputs.EXIT_CODE > env.severity_level }}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Critical vulnerabilities found :(')


  upload-artifact:
    runs-on: ubuntu-latest
    needs:
      - test
      - integration-test
      - code-scan
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
      - run: yarn
      - name: Build App
        run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: counter-app
          path: build/

  staging:
    runs-on: ubuntu-latest
    environment: staging
    needs:
      - upload-artifact
    steps:
      - name: Fetch source code files
        uses: actions/checkout@v2
      - name: Deploy to TAS
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: push counter-staging

  production:
    runs-on: ubuntu-latest
    environment: production
    needs:
      - staging
    steps:
      - name: Fetch source code files
        uses: actions/checkout@v2
      - name: Deploy to TAS
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: push counter-prod
