# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Counter Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  node_version: 16.x

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
      - run: yarn
      - name: run yarn audit
        id: run_yarn_audit
        continue-on-error: true
        shell: bash
        run: |
          yarn audit --level high
          exitcode=$?
          Write-Output "::set-output name=exitcode::$exitcode"

      - name: Check yarn audit ${{ steps.run_yarn_audit.outputs.exitcode }}
        if: always()
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('High vulnerabilities found :(')

  test:
    runs-on: ubuntu-latest
    environment: prod
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
      - run: yarn
      - name: Install packages
        run: yarn install
      - name: Run tests
        run: yarn test --ci --watchAll=false

  integration-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
      - name: Install packages
        run: yarn install
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn start

  upload-artifact:
    runs-on: ubuntu-latest
    environment: prod
    needs:
      - test
      - integration-test
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node_version }}
          cache: 'npm'
      - name: Install packages
        run: yarn install
      - name: Build App
        run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: counter-app
          path: build/

  deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs:
      - upload-artifact
    steps:
      - name: Fetch source code files
        uses: actions/checkout@v2
      - name: Deploy to TAS
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: ${{ secrets.CF_API }}
          cf_username: ${{ secrets.CF_USER }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: ${{ secrets.CF_ORG }}
          cf_space: ${{ secrets.CF_SPACE }}
          command: push counter
